backend:
  name: github
  repo: zforbes0/Azoth-AI
  branch: main
  client_id: Ov23liYdFNPlFkVJVV1B

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: public/images/uploads # Media files will be stored in the repo under public/images/uploads
public_folder: /images/uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    extension: "astro"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Publish Date", name: "publishDate", widget: "datetime", required: false }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      
  - name: "pillar-pages"
    label: "Pillar Pages"
    folder: "src/pages/blog"
    filter: {field: "layout", value: "pillar"}
    create: false
    slug: "{{slug}}"
    extension: "astro"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Hero Title", name: "heroTitle", widget: "string", required: false }
      - { label: "Hero Subtitle", name: "heroSubtitle", widget: "text", required: false }
      - { label: "Page Header", name: "pageHeader", widget: "string", required: false }
      - { label: "Page Description", name: "pageDescription", widget: "text", required: false }
      - label: "Statistics"
        name: "stats"
        widget: "list"
        fields:
          - { label: "Value", name: "value", widget: "string" }
          - { label: "Label", name: "label", widget: "string" }
      - { label: "Body Content", name: "body", widget: "markdown" }
      
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "src/pages/index.astro"
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "text", required: false }
          - { label: "Hero Title", name: "heroTitle", widget: "string", required: false }
          - { label: "Hero Subtitle", name: "heroSubtitle", widget: "text", required: false }